[Settings]
ID = "5calls"

[[redirects]]
  from = "/issues/*"
  to = "https://api.5calls.org/v1/issues/:splat"

[[redirects]]
  from = "/report"
  to = "http://138.68.25.82/report"

[[redirects]]
  from = "/photo/*"
  to = "http://138.68.25.82/photo/:splat"

[[redirects]]
  from = "/admin/refresh"
  to = "http://138.68.25.82/admin/refresh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

