# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
base = "react/"
command = "yarn deploy-js; yarn build-content && cd ..; hugo"
[build.environment]
HUGO_VERSION = '0.74.3'
NETLIFY_USE_YARN = 'true'
RUBY_VERSION = '2.6.2'
YARN_VERSION = '1.22.5'
# need yarn installed manually
# set hugo version for consistency
# don't care about ruby, but the default installs a new version for each build
