[Settings]
ID = "5calls"

[[redirects]]
  from = "/issues/*"
  to = "https://api.5calls.org/v1/callserve/issues/:splat"

[[redirects]]
  from = "/report"
  to = "https://api.5calls.org/v1/report"

[[redirects]]
  from = "/photo/*"
  to = "https://api.5calls.org/v1/callserve/photo/:splat"

[[redirects]]
  from = "/admin/refresh"
  to = "https://api.5calls.org/v1/callserve/admin/refresh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

