# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
command = "cd react; yarn deploy-js; yarn build-content && hugo"
environment = {NETLIFY_USE_YARN = true, HUGO_VERSION = '0.74.3'}
