# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
base = "react/"                                                           # the base is react because that's how we can cache node_modules and reduce the build times
command = "yarn build-js && yarn build-content && cd .. && hugo -b $URL/"
ignore = "false"                                                          # don't skip builds when they only have hugo edits (outside of base)
publish = "/final/"                                                       # we publish back into a directory *inside* of base because we can't specify a publish root above it
[context.deploy-preview]
# deploy previews need a specific url to point at
command = "yarn build-js && yarn build-content && cd .. && hugo -b $DEPLOY_PRIME_URL/"
[build.environment]
# set hugo version for consistency
HUGO_VERSION = '0.133.0'
# need yarn installed manually
NETLIFY_USE_YARN = 'true'
NODE_OPTIONS = '--unhandled-rejections=strict'
# don't care about ruby, but the default installs a new version for each build
RUBY_VERSION = '2.6.2'
YARN_VERSION = '1.22.5'
NODE_VERSION = '22'

# dunno if we can measure how many clients are still using this old endpoint?
[[redirects]]
from = "/report"
to = "https://api.5calls.org/v1/report"

# an easy link for the google drive printables
[[redirects]]
from = "/printables"
to = "https://drive.google.com/drive/folders/1E6NiAF17kHI9-QnlbNjBfhhuD8N48T0L?usp=sharing"

[[redirects]]
from = "/more"
status = 301
to = "/all/"

# fake dynamic paths for group pages
[[redirects]]
from = "/groups/*"
to = "/groups/index.html"
status = 200
force = true

[[redirects]]
from = "/issue/abortion-access-legislation-scotus"
to = "/issue/abortion-scotus-roe-wade-dobbs/"
