name: Lint & Check Formatting

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'


      - name: Install dependencies
        run: yarn install
        working-directory: react

      - name: Run linter
        run: npm run lint
        working-directory: react

  check-formatting:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
        node-version: '22'

     - name: Install dependencies
       run: yarn install
       working-directory: react

     - name: Check code formatting with Prettier
       run: npm run format:test
       working-directory: react
